name: arabsolitaire_workspace
publish_to: none

environment:
  sdk: ^3.12.1

workspace:
  - apps/mobile
  - packages/game_engine
  - packages/game_solver
  - packages/level_generator
  - packages/unity_bridge_contracts

dev_dependencies:
  flutter_lints: ^6.0.0
