name: level_generator
description: Pure Dart level generator for Solitaire Al-Arab.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.1

dependencies:
  game_engine:
    path: ../game_engine
  game_solver:
    path: ../game_solver

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
